### ISSUE TITLE
Existing self signed certificates are recreated at each VM provision

### ISSUE THREAD

**Issue by cycomarcooo** [themejuice/graft#14]
Hi, it appears that each time I create a new tj project, all self signed certificates are regenerated during VM provision. If a previous cert was marked as Trusted for example in macOS keychain, web browsers like Chrome will throw the following error for all ressources : 
Failed to load resource: net::ERR_INSECURE_RESPONSE

From the VM point of view, the creation date of certificate belonging to existing project corresponds to the new project creation date. 

It should be better to not regenerate certs of existing project.

**Comment by ezekg** [comment]
I guess I've never hit this issue because I usually stick to a single project at a time. It looks like [this line](https://github.com/themejuice/graft/blob/master/cookbooks/graft/recipes/certs.rb?ts=2#L30) is the culprit (`-x $FILE`, as it checks if the file exists _and_ is executable, when it really needs to use `-f $FILE` to simply check if the file exists, since `.pem` files are not executable.
